export const data = [
  {
    id: 0,
    jobName: "Frontend Developer",
    companyName: "Medvise.Ai",
    location: "Greater Banglore Area",
    jobType: "Remote",
    duration: "full-time",
    position: "Senior",
    salaryRange: "50k-60k",
    datePosted: "3 days ago",
    country: "India",
    employees: "10-20 employees",
    skills: "HTML, web-development, CSS, JS",
    industry: "Information Technology",
    saved: false,
    companyDesc:
      "At SPARKLIN, we come together to advance human experience—a pursuit to make each human experience a better life. We take on complicated, world-scale challenges—venturing into the unseen, the not-done-before, continuously. We look beyond the rhetoric, the template answers. We review the challenges through the lens of First Principles. We apply creative thinking, art & science to make new connections, develop fresh strategies and in some cases, create new businesses.We love challenges. We love our work—it’s evolutionary, each step adding to a better tomorrow. We are crazy—curious, unconventional, analytical, artistic. We are a hungry bunch of Polymaths—striving to know more about more things.",
    jobDesc:
      "We are seeking a talented and motivated Full-Time Frontend Developer (Swift) to join our dynamic team. As a Swift Developer, you will be responsible for developing high-quality iOS applications for our clients. If you are passionate about technology and want to work in a fast-paced and exciting environment, then we want to hear from you.",
    responsibilities: [
      "Design and build high-quality systems using Next.js, React and Typescript",
      "Consistently write well tested, readable, secure, and accessible code",
      "Contribute to and guide architectural and technology discussions for the team",
      "Help to define and coach engineering best practices in the team, fostering a culture of quality, pair programming, clean coding, and test-driven development.",
      "Strengthen the team’s agile practices through continuous improvement activities",
      "Effectively use written, verbal, and visual communication to facilitate technical discussion and share ideas",
      "Help build and contribute to an awesome team culture",
    ],
    reqSkills: ["Web Developement", "Html", "CSS", "Javascript", "React", "Next.js", "Tailwind"],
  },

  {
    id: 1,
    jobName: "Frontend Developer",
    companyName: "Medvise.Ai",
    location: "Greater Banglore Area",
    jobType: "Remote",
    duration: "full-time",
    position: "Assosiate",
    salaryRange: "50k-60k",
    datePosted: "3 days ago",
    country: "India",
    employees: "10-20 employees",
    skills: "HTML, web-development, CSS, JS",
    industry: "Information Technology",
    saved: false,
    companyDesc:
      "At SPARKLIN, we come together to advance human experience—a pursuit to make each human experience a better life. We take on complicated, world-scale challenges—venturing into the unseen, the not-done-before, continuously. We look beyond the rhetoric, the template answers. We review the challenges through the lens of First Principles. We apply creative thinking, art & science to make new connections, develop fresh strategies and in some cases, create new businesses.We love challenges. We love our work—it’s evolutionary, each step adding to a better tomorrow. We are crazy—curious, unconventional, analytical, artistic. We are a hungry bunch of Polymaths—striving to know more about more things.",
    jobDesc:
      "We are seeking a talented and motivated Full-Time Frontend Developer (Swift) to join our dynamic team. As a Swift Developer, you will be responsible for developing high-quality iOS applications for our clients. If you are passionate about technology and want to work in a fast-paced and exciting environment, then we want to hear from you.",
    responsibilities: [
      "Design and build high-quality systems using Next.js, React and Typescript",
      "Consistently write well tested, readable, secure, and accessible code",
      "Contribute to and guide architectural and technology discussions for the team",
      "Help to define and coach engineering best practices in the team, fostering a culture of quality, pair programming, clean coding, and test-driven development.",
      "Strengthen the team’s agile practices through continuous improvement activities",
      "Effectively use written, verbal, and visual communication to facilitate technical discussion and share ideas",
      "Help build and contribute to an awesome team culture",
    ],
    reqSkills: ["Web Developement", "Html", "CSS", "Javascript", "React", "Next.js", "Tailwind"],
  },
  {
    id: 2,
    jobName: "Frontend Developer",
    companyName: "Medvise.Ai",
    location: "Greater Banglore Area",
    jobType: "Remote",
    duration: "full-time",
    position: "Junior",
    salaryRange: "50k-60k",
    datePosted: "3 days ago",
    country: "India",
    employees: "10-20 employees",
    skills: "HTML, web-development, CSS, JS",
    industry: "Information Technology",
    saved: false,
    companyDesc:
      "At SPARKLIN, we come together to advance human experience—a pursuit to make each human experience a better life. We take on complicated, world-scale challenges—venturing into the unseen, the not-done-before, continuously. We look beyond the rhetoric, the template answers. We review the challenges through the lens of First Principles. We apply creative thinking, art & science to make new connections, develop fresh strategies and in some cases, create new businesses.We love challenges. We love our work—it’s evolutionary, each step adding to a better tomorrow. We are crazy—curious, unconventional, analytical, artistic. We are a hungry bunch of Polymaths—striving to know more about more things.",
    jobDesc:
      "We are seeking a talented and motivated Full-Time Frontend Developer (Swift) to join our dynamic team. As a Swift Developer, you will be responsible for developing high-quality iOS applications for our clients. If you are passionate about technology and want to work in a fast-paced and exciting environment, then we want to hear from you.",
    responsibilities: [
      "Design and build high-quality systems using Next.js, React and Typescript",
      "Consistently write well tested, readable, secure, and accessible code",
      "Contribute to and guide architectural and technology discussions for the team",
      "Help to define and coach engineering best practices in the team, fostering a culture of quality, pair programming, clean coding, and test-driven development.",
      "Strengthen the team’s agile practices through continuous improvement activities",
      "Effectively use written, verbal, and visual communication to facilitate technical discussion and share ideas",
      "Help build and contribute to an awesome team culture",
    ],
    reqSkills: ["Web Developement", "Html", "CSS", "Javascript", "React", "Next.js", "Tailwind"],
  },
  {
    id: 3,
    jobName: "Frontend Developer",
    companyName: "Medvise.Ai",
    location: "Greater Banglore Area",
    jobType: "Remote",
    duration: "full-time",
    position: "Mid-Senior",
    salaryRange: "50k-60k",
    datePosted: "3 days ago",
    country: "India",
    employees: "10-20 employees",
    skills: "HTML, web-development, CSS, JS",
    industry: "Information Technology",
    saved: false,
    companyDesc:
      "At SPARKLIN, we come together to advance human experience—a pursuit to make each human experience a better life. We take on complicated, world-scale challenges—venturing into the unseen, the not-done-before, continuously. We look beyond the rhetoric, the template answers. We review the challenges through the lens of First Principles. We apply creative thinking, art & science to make new connections, develop fresh strategies and in some cases, create new businesses.We love challenges. We love our work—it’s evolutionary, each step adding to a better tomorrow. We are crazy—curious, unconventional, analytical, artistic. We are a hungry bunch of Polymaths—striving to know more about more things.",
    jobDesc:
      "We are seeking a talented and motivated Full-Time Frontend Developer (Swift) to join our dynamic team. As a Swift Developer, you will be responsible for developing high-quality iOS applications for our clients. If you are passionate about technology and want to work in a fast-paced and exciting environment, then we want to hear from you.",
    responsibilities: [
      "Design and build high-quality systems using Next.js, React and Typescript.",
      "Consistently write well tested, readable, secure, and accessible code.",
      "Contribute to and guide architectural and technology discussions for the team.",
      "Help to define and coach engineering best practices in the team, fostering a culture of quality, pair programming, clean coding, and test-driven development.",
      "Strengthen the team’s agile practices through continuous improvement activities.",
      "Effectively use written, verbal, and visual communication to facilitate technical discussion and share ideas.",
      "Help build and contribute to an awesome team culture.",
    ],
    reqSkills: ["Web Developement", "Html", "CSS", "Javascript", "React", "Next.js", "Tailwind"],
  },
  {
    id: 4,
    jobName: "Frontend Developer",
    companyName: "Medvise.Ai",
    location: "Greater Banglore Area",
    jobType: "Remote",
    duration: "full-time",
    position: "Mid-Senior",
    salaryRange: "50k-60k",
    datePosted: "3 days ago",
    country: "India",
    employees: "10-20 employees",
    skills: "HTML, web-development, CSS, JS",
    industry: "Information Technology",
    saved: false,
    companyDesc:
      "At SPARKLIN, we come together to advance human experience—a pursuit to make each human experience a better life. We take on complicated, world-scale challenges—venturing into the unseen, the not-done-before, continuously. We look beyond the rhetoric, the template answers. We review the challenges through the lens of First Principles. We apply creative thinking, art & science to make new connections, develop fresh strategies and in some cases, create new businesses.We love challenges. We love our work—it’s evolutionary, each step adding to a better tomorrow. We are crazy—curious, unconventional, analytical, artistic. We are a hungry bunch of Polymaths—striving to know more about more things.",
    jobDesc:
      "We are seeking a talented and motivated Full-Time Frontend Developer (Swift) to join our dynamic team. As a Swift Developer, you will be responsible for developing high-quality iOS applications for our clients. If you are passionate about technology and want to work in a fast-paced and exciting environment, then we want to hear from you.",
    responsibilities: [
      "Design and build high-quality systems using Next.js, React and Typescript.",
      "Consistently write well tested, readable, secure, and accessible code.",
      "Contribute to and guide architectural and technology discussions for the team.",
      "Help to define and coach engineering best practices in the team, fostering a culture of quality, pair programming, clean coding, and test-driven development.",
      "Strengthen the team’s agile practices through continuous improvement activities.",
      "Effectively use written, verbal, and visual communication to facilitate technical discussion and share ideas.",
      "Help build and contribute to an awesome team culture.",
    ],
    reqSkills: ["Web Developement", "Html", "CSS", "Javascript", "React", "Next.js", "Tailwind"],
  },
];
